# Generated by Django 5.2.17 on 2026-10-02 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_history_actor_id_label'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('DAY_OF', 'Day of')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('error', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='tenants.tenant')),
            ],
            options={
                'db_table': 'reminders_reminder',
                'ordering': ('scheduled_for',),
                'indexes': [models.Index(fields=['tenant_id', 'status', 'scheduled_for'], name='idx_reminders_t_stat_sched')],
                'constraints': [models.UniqueConstraint(fields=('appointment', 'kind'), name='uniq_reminder_appointment_kind')],
            },
        ),
    ]
