# Generated by Django 5.2.17 on 2026-10-02 16:27

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_history_actor_id_label'),
        ('customers', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('BOOKING_CONFIRMED', 'Booking confirmed'), ('PAYMENT_SUCCESS', 'Payment success'), ('APPOINTMENT_CANCELLED', 'Appointment cancelled'), ('APPOINTMENT_RESCHEDULED', 'Appointment rescheduled'), ('REMINDER_UPCOMING', 'Reminder upcoming'), ('REMINDER_DAY_OF', 'Reminder day of')], max_length=40)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('placeholder_keys', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Known placeholder keys for validation', size=None)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_templates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'notifications_notificationtemplate',
                'ordering': ('event', 'channel'),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('BOOKING_CONFIRMED', 'Booking confirmed'), ('PAYMENT_SUCCESS', 'Payment success'), ('APPOINTMENT_CANCELLED', 'Appointment cancelled'), ('APPOINTMENT_RESCHEDULED', 'Appointment rescheduled'), ('REMINDER_UPCOMING', 'Reminder upcoming'), ('REMINDER_DAY_OF', 'Reminder day of')], max_length=40)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('to_email', models.EmailField(blank=True, max_length=254)),
                ('to_phone', models.CharField(blank=True, max_length=32)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='appointments.appointment')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='tenants.tenant')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationtemplate')),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'event', 'channel'), name='uniq_notificationtemplate_tenant_event_channel'),
        ),
    ]
