# Generated by Django 5.2.17 on 2026-09-28 17:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('providers', '0002_alter_provider_email_alter_provider_phone'),
        ('services', '0002_service_provider'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField(db_index=True, help_text='Slot start, stored UTC.')),
                ('end_at', models.DateTimeField(db_index=True, help_text='Consultation end = start + duration.')),
                ('timezone', models.CharField(help_text='Tenant TZ captured for rendering.', max_length=64)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending payment'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show'), ('RESCHEDULED', 'Rescheduled'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING_PAYMENT', max_length=16)),
                ('slot_hold_expires_at', models.DateTimeField(blank=True, db_index=True, help_text='When a PENDING_PAYMENT hold lapses; swept to EXPIRED (plan §5 layer 3).', null=True)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=500)),
                ('customer_notes', models.TextField(blank=True, default='')),
                ('created_via', models.CharField(choices=[('api', 'Client API'), ('admin', 'Admin console')], default='api', max_length=16)),
                ('customer', models.ForeignKey(help_text='Who this booking belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='customers.customer')),
                ('provider', models.ForeignKey(help_text='Denormalised from `service` so the overlap exclusion constraint can key on the provider directly (plan §5 layer 2).', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='providers.provider')),
                ('rescheduled_from', models.ForeignKey(blank=True, help_text='The appointment this one replaced (atomic cancel + create, plan §5).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rescheduled_to', to='appointments.appointment')),
                ('service', models.ForeignKey(help_text='PROTECT: a service referenced by a booking can never be hard-deleted (plan §2).', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.service')),
                ('tenant', models.ForeignKey(help_text='The practice this booking belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, default='', max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('actor_type', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin user'), ('system', 'Background job')], default='system', max_length=16)),
                ('actor_id', models.CharField(blank=True, default='', max_length=36)),
                ('note', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='appointments.appointment')),
            ],
            options={
                'db_table': 'appointment_status_history',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant_id', 'status'], name='idx_appts_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['provider_id', 'start_at'], name='idx_appts_provider_start'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['customer_id', 'start_at'], name='idx_appts_customer_start'),
        ),
        migrations.AddIndex(
            model_name='appointmentstatushistory',
            index=models.Index(fields=['appointment_id', 'created_at'], name='idx_history_appt_time'),
        ),
    ]
