# Generated by Django 5.2.17 on 2026-09-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_no_provider_overlap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentstatushistory',
            name='actor_id',
            field=models.CharField(blank=True, default='', help_text="Who acted. A bare user/customer UUID, or a typed label such as 'payment:<uuid>' for a capture-driven confirmation, so the audit leg says *what* paid for the slot and not merely that something did.", max_length=64),
        ),
    ]
