# Generated by Django 5.2.17 on 2026-09-28 16:35

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)])),
                ('buffer_before_minutes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(240)])),
                ('buffer_after_minutes', models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(240)])),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], db_index=True, default='ACTIVE', max_length=16)),
                ('requires_payment', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(help_text='The practice this service belongs to; PROTECT so a referenced service can never be hard-deleted once appointments exist.', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='tenants.tenant')),
            ],
            options={
                'db_table': 'services',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='idx_services_tenant_status')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_services_tenant_slug')],
            },
        ),
    ]
