# Generated by Django 5.2.17 on 2026-09-28 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Who delivers this service. Required before the service can be booked/slotted; nullable only for rows created before providers existed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='providers.provider'),
        ),
    ]
