# Generated by Django 5.2.17 on 2026-09-28 16:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(help_text='The practice this provider works for.', on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'providers',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['tenant_id', 'is_active'], name='idx_providers_tenant_active')],
            },
        ),
    ]
