# Generated by Django 5.2.17 on 2026-09-28 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(default='user', max_length=32)),
                ('actor_id', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='idx_audit_tenant_created'), models.Index(fields=['entity_type', 'entity_id'], name='idx_audit_entity')],
            },
        ),
    ]
