# Generated by Django 5.2.17 on 2026-09-28 17:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOtp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(help_text='Normalized E.164 phone.', max_length=20)),
                ('salt', models.CharField(editable=False, max_length=32)),
                ('code_hash', models.CharField(editable=False, max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True, editable=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
            ],
            options={
                'db_table': 'phone_otps',
                'ordering': ('-created_at',),
            },
        ),
    ]
