# Generated by Django 5.2.17 on 2026-09-28 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_otp', '0001_initial'),
        ('customers', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Filled in on successful verification only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_codes', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='tenant',
            field=models.ForeignKey(help_text='The practice the code was issued for.', on_delete=django.db.models.deletion.PROTECT, related_name='otp_codes', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='phoneotp',
            index=models.Index(fields=['tenant_id', 'phone', 'created_at'], name='idx_otp_tenant_phone_window'),
        ),
        migrations.AddIndex(
            model_name='phoneotp',
            index=models.Index(fields=['tenant_id', 'phone', 'consumed_at'], name='idx_otp_tenant_phone_consumed'),
        ),
    ]
