# Generated by Django 5.2.17 on 2026-09-28 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='The Idempotency-Key header value.', max_length=72)),
                ('endpoint', models.CharField(help_text="Route scoping the key, e.g. 'appointments'.", max_length=72)),
                ('object_id', models.CharField(blank=True, default='', help_text='Primary key of the object created for this key, once it exists.', max_length=36)),
                ('tenant', models.ForeignKey(help_text='The practice the request ran against.', on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='tenants.tenant')),
            ],
            options={
                'db_table': 'idempotency_records',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('tenant', 'endpoint', 'key'), name='uniq_idempotency_tenant_endpoint_key')],
            },
        ),
    ]
