# Generated by Django 5.2.17 on 2026-09-28 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, help_text='E.164 phone number, e.g. +919876543210. Unique per tenant.', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Optional per D3. Unique per tenant when present.', max_length=254, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(help_text='The practice this client belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'customers',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant_id', 'phone'], name='idx_customers_tenant_phone'), models.Index(fields=['tenant_id', 'is_active'], name='idx_customers_tenant_active')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'phone'), name='uniq_customer_phone_per_tenant'), models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('tenant', 'email'), name='uniq_customer_email_per_tenant')],
            },
        ),
    ]
