# Generated by Django 5.2.17 on 2026-09-28 09:53

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=16)),
                ('profile', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ('name',),
            },
        ),
    ]
