from __future__ import annotations

from datetime import timedelta

from celery.schedules import crontab

from common.logging import JSON_FORMATTER, PLAIN_FORMATTER
from config.paths import BASE_DIR, env

REPO_DIR = BASE_DIR.parent

SECRET_KEY = env.str("DJANGO_SECRET_KEY")
DEBUG = env.bool("DJANGO_DEBUG")
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS")

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    # third party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "drf_spectacular",
    "django_celery_beat",
    "corsheaders",
    # local
    "apps.tenants",
    "apps.accounts",
    "apps.auth_otp",
    "apps.customers",
    "apps.providers",
    "apps.services",
    "apps.scheduling",
    "apps.appointments",
    "apps.payments",
    "apps.notifications",
    "apps.reminders",
    "apps.reports",
    "apps.audit",
    "common",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Before CommonMiddleware, per django-cors-headers' own ordering rule: a
    # response generated by CommonMiddleware (a redirect, for instance) would
    # otherwise leave without CORS headers and be unreadable by the browser.
    "corsheaders.middleware.CorsMiddleware",
    "common.middleware.RequestIDMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # After AuthenticationMiddleware: it prefers `request.user.tenant` for
    # session-authenticated traffic. JWT requests are re-resolved in
    # `TenantScopedViewSet.get_tenant()` because DRF authenticates later.
    "apps.tenants.middleware.TenantMiddleware",
    # After AuthenticationMiddleware/TenantMiddleware: binds actor + request
    # for the `audit()` helper (JWT actors are added by views explicitly).
    "apps.audit.middleware.AuditContextMiddleware",
    # NB the path: there is no `django.middleware.messages`. The admin system
    # check swallows the resulting ImportError and reports admin.E409 instead,
    # which is a misleading error for a missing module.
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Slug of the tenant used when a request carries no tenant hint (bare-domain
# single-tenant installs, the V1 case). Empty means "resolve from the host
# only", and a request that names no tenant simply has none bound.
DEFAULT_TENANT_SLUG = env.str("DJANGO_DEFAULT_TENANT_SLUG", default="") or None

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# ---------------------------------------------------------------- database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env.str("DJANGO_DB_NAME"),
        "USER": env.str("DJANGO_DB_USER"),
        "PASSWORD": env.str("DJANGO_DB_PASSWORD"),
        "HOST": env.str("DJANGO_DB_HOST"),
        "PORT": env.int("DJANGO_DB_PORT"),
        "CONN_MAX_AGE": env.int("DJANGO_DB_CONN_MAX_AGE"),
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {
            "sslmode": env.str("DJANGO_DB_SSLMODE"),
            "connect_timeout": 10,
        },
        "TEST": {
            "NAME": env.str("DJANGO_TEST_DB_NAME", default=f"test_{env('DJANGO_DB_NAME')}"),
        },
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.User"

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

# ---------------------------------------------------------------- i18n / tz
LANGUAGE_CODE = "en-us"
TIME_ZONE = env.str("DJANGO_DEFAULT_TIMEZONE")
USE_I18N = True
USE_TZ = True
DATE_FORMAT = "Y-m-d"
DATETIME_FORMAT = "Y-m-d H:i:s"

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").is_dir() else []
STORAGES = {
    "default": {"BACKEND": env.str("DJANGO_STORAGE_BACKEND")},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}
if env.bool("DJANGO_USE_TLS"):
    STORAGES["default"] = {"BACKEND": "storages.backends.s3.S3Storage"}

# ---------------------------------------------------------------- drf
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "apps.accounts.authentication.AdminJWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
    "DEFAULT_PAGINATION_CLASS": "common.pagination.StandardPagination",
    "PAGE_SIZE": env.int("DJANGO_PAGINATION_PAGE_SIZE"),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
        "rest_framework.filters.SearchFilter",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "common.exceptions.api_exception_handler",
    "DEFAULT_THROTTLE_CLASSES": [
        "common.throttles.AnonRateThrottle",
        "common.throttles.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": env.str("DJANGO_THROTTLE_ANON_RATE"),
        "user": env.str("DJANGO_THROTTLE_USER_RATE"),
        "otp_request": env.str("DJANGO_THROTTLE_OTP_REQUEST_RATE"),
        "otp_verify": env.str("DJANGO_THROTTLE_OTP_VERIFY_RATE"),
        "login": env.str("DJANGO_THROTTLE_LOGIN_RATE"),
        "booking": env.str("DJANGO_THROTTLE_BOOKING_RATE"),
        "availability": env.str("DJANGO_THROTTLE_AVAILABILITY_RATE"),
        "webhook": env.str("DJANGO_THROTTLE_WEBHOOK_RATE"),
        "payment": env.str("DJANGO_THROTTLE_PAYMENT_RATE"),
    },
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.NamespaceVersioning",
    "DEFAULT_VERSION": "v1",
    "ALLOWED_VERSIONS": ["v1"],
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=env.int("DJANGO_ACCESS_TOKEN_LIFETIME_MINUTES")),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=env.int("DJANGO_REFRESH_TOKEN_LIFETIME_DAYS")),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "TOKEN_TYPE_CLAIM": "token_type",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Booking & Management API",
    "DESCRIPTION": "Multi-tenant-ready appointment booking, payments and notifications API.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": "/api/v[0-9]",
    "SERVERS": [{"url": "/api/v1"}],
    "COMPONENT_SPLIT_REQUEST": True,
    "SORT_OPERATIONS": False,
    # Several models have a `status`/`type` choice set (appointments, payment
    # orders, availability exceptions). Without names, the schema generator
    # disambiguates them as `Status`, `Status2`, `Status3`, which is stable
    # only until the next model arrives - so they are named here on purpose.
    "ENUM_NAME_OVERRIDES": {
        "AppointmentStatusEnum": "apps.appointments.models.AppointmentStatus.choices",
        "AppointmentActorEnum": "apps.appointments.models.AppointmentActor.choices",
        "CreatedViaEnum": "apps.appointments.models.CreatedVia.choices",
        "PaymentOrderStatusEnum": "apps.payments.models.PaymentOrderStatus.choices",
        "RefundStatusEnum": "apps.payments.models.RefundStatus.choices",
        "PaymentEventOutcomeEnum": "apps.payments.models.PaymentEventOutcome.choices",
        "ExceptionTypeEnum": "apps.scheduling.models.ExceptionType.choices",
    },
    "POSTPROCESSING_HOOKS": [
        "drf_spectacular.hooks.postprocess_schema_enums",
    ],
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}

# OpenAPI schema + interactive UI: mounted where SERVE_API_DOCS is on
# (dev + test, never prod).
SERVE_API_DOCS = env.bool("DJANGO_SERVE_API_DOCS", default=DEBUG)

# ------------------------------------------------- OTP (plan §4, S §A3)
# Code lifetime and guess cap are hard security bounds, so both are settings
# rather than magic constants. `DJANGO_OTP_SMS_BACKEND` picks the delivery
# channel: only `console` exists in Phase 4 (SMS/WhatsApp arrive in Phase 7 §7).
# `DJANGO_DEFAULT_COUNTRY_CODE` is the assumption behind E.164 normalisation
# of phone numbers typed without a leading `+` (see apps/customers/phone.py).
OTP_LIFETIME_MINUTES = env.int("DJANGO_OTP_LIFETIME_MINUTES")
OTP_MAX_ATTEMPTS = env.int("DJANGO_OTP_MAX_ATTEMPTS")
OTP_SMS_BACKEND = env.str("DJANGO_OTP_SMS_BACKEND")
DEFAULT_COUNTRY_CODE = env.str("DJANGO_DEFAULT_COUNTRY_CODE")

# ---------------------------------------------------------------- cache
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": env.str("DJANGO_CACHE_URL"),
        "KEY_PREFIX": env.str("DJANGO_CACHE_KEY_PREFIX", default="lawyer"),
    }
}

# ---------------------------------------------------------------- celery
CELERY_BROKER_URL = env.str("DJANGO_CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = env.str("DJANGO_CELERY_RESULT_BACKEND")
CELERY_TASK_ALWAYS_EAGER = env.bool("DJANGO_CELERY_TASK_ALWAYS_EAGER")
CELERY_TASK_EAGER_PROPAGATES = env.bool("DJANGO_CELERY_TASK_EAGER_PROPAGATES")
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 4
CELERY_WORKER_MAX_TASKS_PER_CHILD = 500
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_ROUTES = {
    "notifications.*": {"queue": "notifications"},
    "payments.*": {"queue": "payments"},
    "appointments.*": {"queue": "default"},
}
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# ---------------------------------------------------------------- email
EMAIL_BACKEND = env.str("DJANGO_EMAIL_BACKEND")
DEFAULT_FROM_EMAIL = env.str("DJANGO_DEFAULT_FROM_EMAIL")
SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_HOST = env.str("DJANGO_EMAIL_HOST", default="mailhog")
EMAIL_PORT = env.int("DJANGO_EMAIL_PORT", default=1025)
EMAIL_HOST_USER = env.str("DJANGO_EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env.str("DJANGO_EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env.bool("DJANGO_EMAIL_USE_TLS", default=False)

# ---------------------------------------------------------------- domain defaults
DEFAULT_CURRENCY = env.str("DJANGO_DEFAULT_CURRENCY")
SLOT_HOLD_MINUTES = env.int("DJANGO_SLOT_HOLD_MINUTES")
CANCELLATION_POLICY_MIN_HOURS = env.int("DJANGO_CANCELLATION_POLICY_MIN_HOURS")
MAX_ACTIVE_HOLDS_PER_CUSTOMER = env.int("DJANGO_MAX_ACTIVE_HOLDS_PER_CUSTOMER")

# Unpaid holds are a *promise*, not a reservation: the sweep releases them when
# the window closes. Run at least once per SLOT_HOLD_MINUTES so a lapsed hold
# frees its slot on schedule instead of waiting for the next booking attempt to
# trip over it.
CELERY_BEAT_SCHEDULE = {
    "expire-appointment-holds": {
        "task": "appointments.expire_slot_holds",
        "schedule": crontab(minute=f"*/{max(1, min(15, SLOT_HOLD_MINUTES))}"),
    },
    # Backstop for a webhook the gateway never managed to deliver (plan §6):
    # open orders older than PAYMENT_RECONCILE_MINUTES are compared against
    # the gateway's own answer and closed if the money never arrived.
    "reconcile-pending-payments": {
        "task": "payments.reconcile_pending_payments",
        "schedule": crontab(minute=0, hour="*"),
    },
}
BOOKING_LEAD_TIME_HOURS = env.int("DJANGO_BOOKING_LEAD_TIME_HOURS")
BOOKING_LOOKAHEAD_DAYS = env.int("DJANGO_BOOKING_LOOKAHEAD_DAYS")
AVAILABILITY_LEAD_TIME_MINUTES = env.int("DJANGO_AVAILABILITY_LEAD_TIME_MINUTES")
AVAILABILITY_HORIZON_DAYS = env.int("DJANGO_AVAILABILITY_HORIZON_DAYS")
AVAILABILITY_CACHE_SECONDS = env.int("DJANGO_AVAILABILITY_CACHE_SECONDS")

PAYMENT_GATEWAY = env.str("DJANGO_PAYMENT_GATEWAY")
#: `test` or `live`. Stamped onto every order, and a capture is only applied to
#: an order of the same mode (S §A5: a test-mode order can never confirm a live
#: booking). Never inferred from the key material - an operator setting the
#: wrong thing here is exactly the case the check exists for.
PAYMENT_MODE = env.str("DJANGO_PAYMENT_MODE")
RAZORPAY_KEY_ID = env.str("DJANGO_RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = env.str("DJANGO_RAZORPAY_KEY_SECRET")
RAZORPAY_WEBHOOK_SECRET = env.str("DJANGO_RAZORPAY_WEBHOOK_SECRET")
#: How long an open order may sit before the reconcile task asks the gateway
#: what really happened. Comfortably above the slot hold, so the normal
#: resolution (hold expiry) has usually already closed the order.
PAYMENT_RECONCILE_MINUTES = env.int("DJANGO_PAYMENT_RECONCILE_MINUTES")

# ---------------------------------------------------------------- security
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True
CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS")

# ------------------------------------------------------------------- CORS
# The dependency (`django-cors-headers`) is declared in pyproject; before this
# was wired the settings below were read and discarded, so a browser calling
# the API cross-origin got no `Access-Control-Allow-Origin` and the request
# failed in the preflight.
#
# Local dev is normally *same-origin* — the Next app on :8000 proxies `/api/v1`
# to the backend (frontend `next.config.ts`, `API_PROXY_TARGET`) — so these
# origins exist for the split-port setup and for a deployed API on its own
# origin. `prod.py` overrides the default and refuses to start empty.
CORS_ALLOWED_ORIGINS = env.list(
    "DJANGO_CORS_ALLOWED_ORIGINS",
    default=["http://localhost:8000", "http://localhost:3000"],
)
# Auth cookies are HttpOnly and set by this backend, so every call is
# credentialed and `Allow-Credentials` is required. That pairing is exactly why
# the allowlist must stay an explicit origin list: with credentials, a wildcard
# is invalid per spec and unsafe per security.md §A (never `*` + credentials).
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_METHODS = ["GET", "POST", "PATCH", "PUT", "DELETE", "OPTIONS"]
# `Authorization`, `Content-Type`, `X-Request-ID` (client.ts) and
# `Idempotency-Key` (Phase 5/6 booking and payment calls) must all clear preflight.
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-language",
    "authorization",
    "content-type",
    "idempotency-key",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-request-id",
]
# Scoped to the API: the Django admin must never be reachable cross-origin with
# a session cookie, and neither should `/admin/`'s own asset requests.
CORS_URLS_REGEX = r"^/api/.*$"

if "*" in CORS_ALLOWED_ORIGINS:
    raise RuntimeError(
        "DJANGO_CORS_ALLOWED_ORIGINS must list exact origins. A wildcard cannot be "
        "paired with CORS_ALLOW_CREDENTIALS (security.md §A: never `*` + credentials)."
    )

# ---------------------------------------------------------------- logging
LOG_LEVEL = env.str("DJANGO_LOG_LEVEL")
LOG_JSON = env.bool("DJANGO_LOG_JSON")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": JSON_FORMATTER,
        "plain": PLAIN_FORMATTER,
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json" if LOG_JSON else "plain",
        },
    },
    "root": {"handlers": ["console"], "level": LOG_LEVEL},
    "loggers": {
        "django": {"handlers": ["console"], "level": LOG_LEVEL, "propagate": False},
        "django.db.backends": {"handlers": ["console"], "level": "WARNING", "propagate": False},
        "apps": {"handlers": ["console"], "level": LOG_LEVEL, "propagate": False},
        "common": {"handlers": ["console"], "level": LOG_LEVEL, "propagate": False},
    },
}
