# Generated by Django 5.2.17 on 2026-09-28 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('customers', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(default='razorpay', max_length=32)),
                ('gateway_order_id', models.CharField(blank=True, help_text='Gateway order id (Phase 6); NULL until then, and NULLs do not collide (plan §3: unique gateway ids).', max_length=64, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='CREATED', max_length=16)),
                ('receipt', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_order', to='appointments.appointment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='tenants.tenant')),
            ],
            options={
                'db_table': 'payment_orders',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='idx_orders_tenant_status'), models.Index(fields=['appointment_id'], name='idx_orders_appointment')],
            },
        ),
    ]
