# Generated by Django 5.2.17 on 2026-09-28 18:35

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_no_provider_overlap"),
        ("customers", "0001_initial"),
        ("payments", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(max_length=32)),
                ('gateway_payment_id', models.CharField(help_text='Gateway payment id. Unique so a replayed capture cannot mint a second row.', max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=16)),
                ('method', models.CharField(blank=True, default='', help_text='Gateway instrument (card/upi/netbanking) when reported.', max_length=32)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(max_length=32)),
                ('event_id', models.CharField(max_length=80)),
                ('event_type', models.CharField(blank=True, default='', max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Parsed body, stored as received. Signature is verified over the raw bytes.')),
                ('signature', models.CharField(blank=True, default='', max_length=256)),
                ('gateway_order_id', models.CharField(blank=True, default='', max_length=64)),
                ('outcome', models.CharField(choices=[('RECEIVED', 'Received'), ('APPLIED', 'Applied'), ('DUPLICATE', 'Duplicate'), ('UNMATCHED', 'Unmatched'), ('IGNORED', 'Ignored'), ('FAILED', 'Failed')], default='RECEIVED', max_length=16)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_events',
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING_ACTION', 'Pending action'), ('SETTLED', 'Settled'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_ACTION', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('gateway_refund_id', models.CharField(blank=True, help_text='Set by an admin when the dashboard confirms the refund id.', max_length=64, null=True, unique=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'refunds',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text="Mirror of the slot hold's expiry; drives `PENDING -> EXPIRED` (plan §6.1).", null=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='gateway_mode',
            field=models.CharField(default='test', help_text='test|live, stamped from settings at creation. A capture for a test-mode order can never confirm a live booking (S §A5).', max_length=8),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When the gateway told us the money landed (never set by a client call).', null=True),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status', 'created_at'], name='idx_orders_status_created'),
        ),
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentorder'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['event_type'], name='idx_payment_events_type'),
        ),
        migrations.AddConstraint(
            model_name='paymentevent',
            constraint=models.UniqueConstraint(fields=('gateway', 'event_id'), name='uniq_payment_events_gateway_event'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_settled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant_id', 'status'], name='idx_payments_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order_id'], name='idx_payments_order'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'SUCCESS')), fields=('order',), name='uniq_payments_order_success'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['tenant_id', 'status'], name='idx_refunds_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment_id'], name='idx_refunds_payment'),
        ),
    ]
