# Generated by Django 5.2.17 on 2026-09-28 16:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('type', models.CharField(choices=[('BLOCKED', 'Blocked'), ('OVERRIDE', 'Override')], db_index=True, default='BLOCKED', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('provider', models.ForeignKey(help_text='Whose calendar this exception edits.', on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='providers.provider')),
            ],
            options={
                'db_table': 'availability_exceptions',
                'ordering': ('date', 'start_time'),
                'indexes': [models.Index(fields=['provider_id', 'date'], name='idx_avexc_provider_date')],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField(help_text='0 = Monday ... 6 = Sunday (ISO weekday).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('provider', models.ForeignKey(help_text='Whose week this is.', on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='providers.provider')),
            ],
            options={
                'db_table': 'availability_rules',
                'ordering': ('weekday', 'start_time'),
                'indexes': [models.Index(fields=['provider_id', 'weekday', 'effective_from', 'effective_to'], name='idx_avrules_provider_weekday')],
            },
        ),
    ]
